[categories]
Food       = ["Groceries", "Restaurant", "Food Misc"]
Home       = ["Home Insurance", "Loan", "Utilities", "Home Maintenance"]
Transport  = ["Fuel", "Public Transport", "Vehicle Maintenance", "Taxi/Rideshare", "Rental", "Vehicle Insurance"]
Health     = ["Self care", "Medical", "Pharmacy", "Health Insurance", "Dental/Vision", "Psi", "Life Insurance"]
Leisure    = ["Sport", "Lessons/Learning", "Subscriptions", "Entertainment"]
Shopping   = ["Clothing", "Shopping Misc", "Media", "Home"]
Travel     = ["Accommodation", "Transport", "Food", "Activities"]
Gifts      = ["Donations", "Charity", "Events"]
Finance    = ["Bank fees", "Investment fees", "Taxes", "Investment"]

[training]
Groceries = ["pewex"]
Restaurant = ["mcdonald", "pizzeria"]
Fuel             = ["orlen", "shell", "bp", "circle k"]
"Taxi/Rideshare" = ["bolt", "uber", "freenow"]
"Public Transport" = ["atac"]
Rental           = ["city-nav", "panek"]
"Self care"      = ["rossmann"]
Pharmacy         = ["apteka dr. max"]
Medical          = ["medical centre"]
Psi              = ["Burrhus Skinner"]
Sport = ["decathlon"]
Subscriptions    = ["netflix", "anthropic"]
Entertainment    = ["ticketone"]
"Lessons/Learning" = ["project invictus"]
Clothing         = ["tk maxx","vinted"]
Home             = ["ikea", "castorama"]
Media            = ["amazon"]
Utilities        = ["t-mobile"]
"Life Insurance" = [""]
Accommodation    = ["booking.com"]
Transport        = ["ryanair", "lufthansa", "virgin", "flixbus"]
Activities       = ["cski-rental]
Donations        = ["unrwa"]
"Bank fees"      = ["ing bank"]
Taxes            = ["dzien dobry urząd skarbowy, daj nam swoje pieniądze"]
